[window]
padding.x = 5
padding.y = 5

# opacity = 0.95

[font]

size = 12.5
normal.family = "JetBrains Mono Nerd Font"
italic.family = "JetBrains Mono Nerd Font"
bold.family = "JetBrains Mono Nerd Font"

# size = 13.5
# normal.family = "UbuntuMono Nerd Font"
# italic.family = "UbuntuMono Nerd Font"
# bold.family = "UbuntuMono Nerd Font"

# normal.family = "Terminess Nerd Font"
# italic.family = "Terminess Nerd Font"
# bold.family = "Terminess Nerd Font"


[colors.primary]
background = '#161616'
foreground = "#f8f8f2"

[colors.normal]
black = "#272822"
red = "#f92672"
green = "#a6e22e"
yellow = "#f4bf75"
blue = "#66d9ef"
magenta = "#ae81ff"
cyan = "#a1efe4"
white = "#f8f8f2"

[colors.bright]
black = "#75715e"
red = "#f92672"
green = "#a6e22e"
yellow = "#f4bf75"
blue = "#66d9ef"
magenta = "#ae81ff"
cyan = "#a1efe4"
white = "#f9f8f5"

[colors.cursor]
text = "#272822"
cursor = "#f8f8f2"
